# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7836f3e0d36c673cc6f706135ed1991f0e45d7187e48291f9a9cb40da0aed387957a602290523116003d69b758fd32814e514535555f8b11a6ae1352c585d948

test:
  secret_key_base: 621633b56ad2f2c66b5127332bf3e4b58857857803afa537bc40762a77f49a31bb871634935d8d7408ce4ee3cad496fce7d4804bbc58ca4d40855628bc0a7bf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
